import { Inter, Oswald } from "next/font/google";
import "./globals.css";
import Navigation from "./_components/Navigation";
import Footer from "./_components/Footer";

const headingFont = Oswald({
  variable: "--font-heading",
  weight: ["300"],
  subsets: ["latin"],
});

const textFont = Inter({
  variable: "--font-text",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${headingFont.variable} ${textFont.className} text-text-primary antialiased`}
      >
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
